# Fondo y texto
background #0b0f14
foreground #98FB98
background_opacity 0.75

# Espacio interior de la ventana
window_padding_width 14

# Fuente
font_family monospace
font_size 13.0

# Cursor
cursor #98FB98
cursor_text_color #0b0f14
cursor_shape beam
cursor_beam_thickness 2
cursor_blink_interval 0.6

# Selección de texto
selection_foreground #0b0f14
selection_background #98FB98

# Historial
scrollback_lines 10000

# Sin sonido de aviso
enable_audio_bell no

# Control remoto
allow_remote_control yes
